### ISSUE TITLE
オープンデータ パーツの修正

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/opendata#19]
以下のパーツが、上部 HTML や下部 HTML 相当のデータをプログラムで出力しており、過剰。
- オープンデータ/データセット
- オープンデータ/アプリ
- オープンデータ/アイデア

上部HTML、ループHTML、下部HTMLをうまく活用できない。

**Comment by sunny4381** [comment]
上部 HTML や下部 HTML 相当のデータをプログラムで出力するのをやめました。

**Comment by ghost** [comment]
分野のページで、右側にでる注目アプリなどのヘッダー部ともっとみるがでなくなっています。

**Comment by sunny4381** [comment]
上部HTMLと下部HTMLの設定が必要です。
詳しくは、devod:00980 を参照してください。
