### ISSUE TITLE
Excel を CSV に変換した際、カラム内の改行は \n で出力される

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/opendata#86]
Excel を CSV に変換した際、カラム内の改行は \n で出力され、行末の改行は \r\n で出力される。

Ruby 標準の CSV は、既定では改行コードを自動判定するが、ヘッダなど 1 行目のカラムに改行文字を含む場合、\n が最初に見つかるので改行コードが \n と判定され、CSV の取り込みに失敗する。

**Comment by itowtips** [comment]
`row_sep: "\r\n"`としても複数の改行コードが混ざっている場合エラーになるようです。
\nで統一してしまうのはどうでしょうか。
#89

**Comment by sunny4381** [comment]
:up:
